name: Buildozer Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install unzip
        run: sudo apt-get install -y unzip

      - name: Check disk space
        run: df -h

      - name: Download and check NDK
        run: |
          # Lade das NDK herunter
          #https://dl.google.com/android/repository/android-ndk-r25b-linux-x86_64.zip -O android-ndk.zip || { echo "Download failed"; exit 1; }
          #wget https://dl.google.com/android/repository/android-ndk-r25b-linux-x86_64.zip
          sudo wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          # Prüfe, ob die Datei existiert
          if [ -f "android-ndk.zip" ]; then
            echo "File downloaded successfully."
          else
            echo "File download failed."
            exit 1
          fi
          
          # Zeige Dateigröße und Typ
          ls -lh android-ndk.zip
          file android-ndk.zip
          
          # Prüfe die Integrität mit md5sum (falls verfügbar)
          md5sum android-ndk.zip || echo "md5sum check failed or command not available."

      - name: Unzip NDK with detailed output
        run: |
          # Erstelle das Zielverzeichnis
          sudo chmod 777 . -R
          sudo mkdir -p .buildozer/android/platform
          
          # Entpacke das NDK und zeige detaillierte Ausgaben an
          #unzip -v android-ndk.zip # -d .buildozer/android/platform || { echo "Unzip failed"; exit 1; }
          sudo chmod 777 . -R
          sudo unzip -q android-ndk-r25b-linux.zip -d .buildozer/android/platform
          ls -l
      - name: Start Docker Buildozer container
        run: |
          # Starte den Buildozer-Container und binde das Arbeitsverzeichnis ein
          sudo docker run --memory=4g --memory-swap=8g --volume "$(pwd)":/home/user/hostcwd kivy/buildozer android debug
