name: Buildozer Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildozer service
        run: |
          docker run --rm -v $(pwd):/home/user/hostcwd -w /home/user/hostcwd \
            kivy/buildozer /bin/bash -c "pip install buildozer && buildozer android debug"