name: Buildozer Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pre-pull Docker image
        run: docker pull kivy/buildozer

      - name: Set up Docker Buildozer service
        run: |
         mkdir -p $(pwd)/.buildozer && \
         docker run --volume "$(pwd)":/home/user/hostcwd \
         --volume "$(pwd)/.buildozer":/home/user/.buildozer \
         --user $(id -u):$(id -g) \
           kivy/buildozer \
           buildozer android debug
