name: Buildozer Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pre-pull Docker image
        run: docker pull kivy/buildozer

      - name: Set up Docker Buildozer service
        run: |
          # Erstelle das NDK-Verzeichnis in der Buildozer-Struktur
          mkdir -p .buildozer/android/platform/android-ndk

          # Lade das NDK manuell herunter
          wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux-x86_64.zip -O android-ndk.zip
          
          # Entpacke das NDK in das Buildozer-Verzeichnis
          unzip -q android-ndk.zip -d .buildozer/android/platform/android-ndk

          # Starte den Buildozer-Container und binde das Arbeitsverzeichnis ein
          docker run --memory=4g --memory-swap=8g --volume "$(pwd)":/home/user/hostcwd kivy/buildozer android debug
