name: Buildozer Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pre-pull Docker image
        run: docker pull kivy/buildozer

      - name: Set up Docker Buildozer service
        run: |
          pwd
          ls -R
          whoami
          sudo chmod 777 -R .
          df -h
          docker run --volume "$(pwd)":/home/user/hostcwd kivy/buildozer android debug
