name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install necessary tools
        run: |
          sudo apt update
          sudo apt install -y git zip unzip wget expect

          # Installiere Android SDK Command Line Tools
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
          unzip commandlinetools-linux-7583922_latest.zip
          rm commandlinetools-linux-7583922_latest.zip
          sudo chown -R $USER:$USER $HOME/android-sdk

          # Setzen der Umgebungsvariablen
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=\$PATH:\$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_ENV

      - name: Accept SDK licenses
        run: |
          echo '#!/usr/bin/expect -f' > accept_licenses.exp
          echo 'set timeout -1' >> accept_licenses.exp
          echo 'spawn sdkmanager --licenses' >> accept_licenses.exp
          echo 'expect "Do you accept the license? [y/n]"' >> accept_licenses.exp
          echo 'send "y\r"' >> accept_licenses.exp
          echo 'expect eof' >> accept_licenses.exp
          chmod +x accept_licenses.exp
          ./accept_licenses.exp

      - name: Clone repository and install dependencies
        run: |
          source $GITHUB_ENV
          git clone https://github.com/xdrfvgz/tts-try
          cd tts-try
          pip install cython setuptools
          pip install buildozer 
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: tts-try/bin/app-debug.apk  # Achte darauf, den korrekten Pfad anzugeben
          if-no-files-found: error
