name: Buildozer Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install unzip
        run: sudo apt-get install -y unzip

      - name: Download and unzip NDK
        run: |
          # Lade das NDK herunter
          wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux-x86_64.zip -O android-ndk.zip
          
          # Überprüfe die Dateigröße
          ls -lh android-ndk.zip
          
          # Entpacke das NDK in das Buildozer-Verzeichnis
          unzip -q android-ndk.zip -d .buildozer/android/platform

      - name: Start Docker Buildozer container
        run: |
          # Starte den Buildozer-Container und binde das Arbeitsverzeichnis ein
          docker run --memory=4g --memory-swap=8g --volume "$(pwd)":/home/user/hostcwd kivy/buildozer android debug
