name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev python3-distutils
          pip3 install --user --upgrade Cython==0.29.33 virtualenv

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmd-tools-version: 12.0

      - name: Install NDK
        run: |
          mkdir -p $HOME/.buildozer/android/platform/
          wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip android-ndk-r25c-linux.zip
          mv android-ndk-r25c $HOME/.buildozer/android/platform/android-ndk-r25c

      - name: Accept licenses and install components
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"
          
      - name: Update buildozer.spec
        run: |
          cat > buildozer.spec << EOF
          [app]
          title = SprachSyntheseApp
          package.name = sprache
          package.domain = org.example
          source.dir = .
          source.include_exts = py,png,jpg,kv,atlas
          source.exclude_exts = spec
          source.exclude_dirs = tests
          version = 0.1
          requirements = python3,kivy,onnxruntime,numpy,sounddevice
          android.permissions = INTERNET, RECORD_AUDIO

          # Android specific settings
          android.ndk = 25c
          android.arch = armeabi-v7a, arm64-v8a
          android.accept_sdk_license = True
          android.api = 30
          android.minapi = 21
          android.sdk = 30
          android.ndk_api = 21
          
          # Skip downloading SDK/NDK as we've already set them up
          android.skip_update = True
          
          # Use the SDK and NDK we've already installed
          android.sdk_path = $ANDROID_SDK_ROOT
          android.ndk_path = $HOME/.buildozer/android/platform/android-ndk-r25c
          
          # Buildozer settings
          log_level = 2
          EOF

      - name: Install buildozer and build
        run: |
          # Install buildozer
          pip3 install --user buildozer
          
          # Create symbolic link to SDK
          mkdir -p $HOME/.buildozer/android/platform
          ln -s $ANDROID_SDK_ROOT $HOME/.buildozer/android/platform/android-sdk
          
          # Clone and build
          git clone https://github.com/xdrfvgz/tts-try
          cd tts-try
          cp ../buildozer.spec .
          pip install cython setuptools
          buildozer android debug -v

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: tts-try/bin/*.apk
          if-no-files-found: error