name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install git zip unzip gradle #openjdk-17-jdk-headless
        #export JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64"
        git clone https://github.com/xdrfvgz/tts-try
        cd tts-try
        gradle wrapper
        ./gradlew wrapper --gradle-version=7.4.2
        ./gradlew assembleDebug -v
        
      
    - name: Upload APK
      uses: actions/upload-artifact@v3  # Aktualisiert auf v3
      with:
        name: app-debug.apk
        path: /home/runner/app-debug.apk
        if-no-files-found: error
