name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Ältere, stabile Version

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev python3-setuptools python3-distutils
          pip3 install --user --upgrade Cython==0.29.33 virtualenv
          export PATH=$PATH:~/.local/bin/

      - name: Install Buildozer
        run: |
          pip3 install --user buildozer
          
      - name: Install Android SDK
        run: |
          mkdir -p $HOME/.buildozer/android/platform/android-sdk
          cd $HOME/.buildozer/android/platform/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
          unzip commandlinetools-linux-7583922_latest.zip
          mkdir -p cmdline-tools/latest
          mv cmdline-tools/* cmdline-tools/latest/ || true
          rm -rf cmdline-tools/latest/cmdline-tools
          export PATH=$PATH:$HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin
          
          # Create license files
          mkdir -p $HOME/.buildozer/android/platform/android-sdk/licenses
          echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > $HOME/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
          echo "84831b9409646a918e30573bab4c9c91346d8abd" > $HOME/.buildozer/android/platform/android-sdk/licenses/android-sdk-preview-license
          
          # Install required SDK components
          cd $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin
          echo "y" | ./sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"
          echo "y" | ./sdkmanager --licenses

      - name: Clone repository and build
        run: |
          git clone https://github.com/xdrfvgz/tts-try
          cd tts-try
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: tts-try/bin/*.apk
          if-no-files-found: error
