name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev python3-distutils
          python -m pip install --upgrade pip
          python -m pip install --user --upgrade Cython==0.29.33 virtualenv
          python -m pip install --user buildozer
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Android SDK
        run: |
          mkdir -p $HOME/android-sdk
          cd $HOME/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
          unzip commandlinetools-linux-7583922_latest.zip
          mkdir -p cmdline-tools/latest
          mv cmdline-tools/* cmdline-tools/latest/ || true
          rm -rf cmdline-tools/latest/cmdline-tools
          
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
          
          # Accept licenses and install components
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"

      - name: Install NDK
        run: |
          mkdir -p $HOME/.buildozer/android/platform/
          wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip android-ndk-r25c-linux.zip
          mv android-ndk-r25c $HOME/.buildozer/android/platform/android-ndk-r25c
          echo "ANDROID_NDK_HOME=$HOME/.buildozer/android/platform/android-ndk-r25c" >> $GITHUB_ENV

      - name: Setup build environment
        run: |
          mkdir -p $HOME/.buildozer/android/platform
          ln -s $HOME/android-sdk $HOME/.buildozer/android/platform/android-sdk

          # Create buildozer.spec
          cat > buildozer.spec << EOF
          [app]
          title = SprachSyntheseApp
          package.name = sprache
          package.domain = org.example
          source.dir = .
          source.include_exts = py,png,jpg,kv,atlas
          source.exclude_exts = spec
          source.exclude_dirs = tests
          version = 0.1
          requirements = python3,kivy,onnxruntime,numpy,sounddevice
          android.permissions = INTERNET, RECORD_AUDIO

          # Android specific settings
          android.archs = armeabi-v7a arm64-v8a
          android.accept_sdk_license = True
          android.api = 30
          android.minapi = 21
          
          # Skip downloading SDK/NDK as we've already set them up
          android.skip_update = True
          
          # Use the SDK and NDK we've already installed
          android.sdk_path = $HOME/android-sdk
          android.ndk_path = $HOME/.buildozer/android/platform/android-ndk-r25c
          
          # Buildozer settings
          log_level = 2
          EOF

      - name: Build APK
        run: |
          git clone https://github.com/xdrfvgz/tts-try
          cd tts-try
          cp ../buildozer.spec .
          python -m pip install --user cython setuptools
          python -m buildozer android debug -v

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: tts-try/bin/*.apk
          if-no-files-found: error
