name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Set JAVA_HOME
      run: |
        echo "JAVA_HOME=$JAVA_HOME_11_X64" >> $GITHUB_ENV
        echo "$JAVA_HOME_11_X64/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip gradle expect
        git clone https://github.com/xdrfvgz/tts-try
        cd tts-try
        
        # Erstelle ein Expect-Skript, um Lizenzen zu akzeptieren
        echo '#!/usr/bin/expect -f
        set timeout -1
        spawn sdkmanager --licenses
        expect {
            "Accept" { send \"y\r\"; exp_continue }
            eof
        }' > accept_licenses.exp
        
        chmod +x accept_licenses.exp
        ./accept_licenses.exp  # Führe das Expect-Skript aus

        pip install cython setuptools
        pip install buildozer 
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: tts-try/bin/app-debug.apk  # Achte darauf, den korrekten Pfad anzugeben
        if-no-files-found: error
