name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROIDSDK: "$HOME/android-sdk"
      ANDROIDNDK: "$HOME/.buildozer/android/platform/android-ndk-r25c"
      ANDROIDAPI: "30"
      ANDROIDMINAPI: "24"
      PACKAGES_PATH: "$HOME/.buildozer/android/packages"

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev python3-distutils
          python -m pip install --upgrade pip
          python -m pip install --user --upgrade Cython==0.29.33 virtualenv
          python -m pip install --user buildozer
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install python-for-android
        run: |
          mkdir -p $HOME/.buildozer/android/platform
          cd $HOME/.buildozer/android/platform
          git clone https://github.com/kivy/python-for-android.git
          cd python-for-android
          python -m pip install -e .

      - name: Setup Android environment
        run: |
          mkdir -p $HOME/android-sdk
          echo "ANDROIDSDK=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROIDNDK=$HOME/.buildozer/android/platform/android-ndk-r25c" >> $GITHUB_ENV
          echo "ANDROIDAPI=30" >> $GITHUB_ENV
          echo "ANDROIDMINAPI=24" >> $GITHUB_ENV
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$PATH:$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools" >> $GITHUB_ENV

          cd $HOME/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
          unzip commandlinetools-linux-7583922_latest.zip
          mkdir -p cmdline-tools/latest
          mv cmdline-tools/* cmdline-tools/latest/ || true
          rm -rf cmdline-tools/latest/cmdline-tools
          
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"

      - name: Install NDK
        run: |
          mkdir -p $HOME/.buildozer/android/platform/
          wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip android-ndk-r25c-linux.zip
          mv android-ndk-r25c $HOME/.buildozer/android/platform/android-ndk-r25c

      - name: Setup build environment
        run: |
          mkdir -p $HOME/.buildozer/android/platform
          ln -s $HOME/android-sdk $HOME/.buildozer/android/platform/android-sdk
          mkdir -p $HOME/.buildozer/android/packages

          cat > buildozer.spec << EOF
          [app]
          title = SprachSyntheseApp
          package.name = sprache
          package.domain = org.example
          source.dir = .
          source.include_exts = py,png,jpg,kv,atlas
          source.exclude_exts = spec
          source.exclude_dirs = tests
          version = 0.1
          requirements = python3,kivy,onnxruntime,numpy,sounddevice
          android.permissions = INTERNET, RECORD_AUDIO

          # Android specific settings
          android.archs = armeabi-v7a
          android.accept_sdk_license = True
          android.api = 30
          android.minapi = 24
          android.ndk = 25c
          android.sdk = 30
          android.ndk_api = 24
          
          android.skip_update = True
          android.sdk_path = $ANDROIDSDK
          android.ndk_path = $ANDROIDNDK
          
          log_level = 2
          p4a.source_dir = $HOME/.buildozer/android/platform/python-for-android
          EOF

      - name: Build APK
        run: |
          cd $GITHUB_WORKSPACE
          cp buildozer.spec $GITHUB_WORKSPACE
          python -m buildozer android debug -v

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: $GITHUB_WORKSPACE/bin/*.apk
          if-no-files-found: error

      - name: Debug environment
        run: |
          echo "ANDROIDSDK: $ANDROIDSDK"
          echo "ANDROIDNDK: $ANDROIDNDK"
          echo "PATH: $PATH"